from turtle import*
speed(-1)
pencolor("red")
fillcolor("red")
begin_fill()
for i in range(2):
    forward(50)
    left(90)
    forward(100)
    left(90)
end_fill()
forward(50)
pencolor("blue")
fillcolor("blue")
begin_fill()
for i in range(2):
    forward(50)
    left(90)
    forward(100)
    left(90)
end_fill()
forward(50)
pencolor("brown")
fillcolor("brown")
begin_fill()
for i in range(2):
    forward(50)
    left(90)
    forward(100)
    left(90)
end_fill()
forward(50)
pencolor("yellow")
fillcolor("yellow")
begin_fill()
for i in range(2):
    forward(50)
    left(90)
    forward(100)
    left(90)
end_fill()
forward(50)
pencolor("grey")
fillcolor("grey")
begin_fill()
for i in range(2):
    forward(50)
    left(90)
    forward(100)
    left(90)
end_fill()
mainloop()